const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={server:'',player:null,data:null,tab:'overview'};
async function api(path,opts={}){const headers=opts.body instanceof FormData?{}:{'Content-Type':'application/json'};const res=await fetch('/api/'+path,{headers,...opts});let data=null;const text=await res.text();try{data=text?JSON.parse(text):null}catch{data={error:text}}if(!res.ok)throw new Error(data?.error||`${res.status} ${res.statusText}`);return data}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';clearTimeout(el.t);el.t=setTimeout(()=>el.className='',3200)}
function serverPath(path){return `booi/${encodeURIComponent(state.server)}/${path}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
async function boot(){try{const h=await api('health');$('#health').textContent='服务正常';$('#health').classList.add('ok');$('#server').innerHTML=h.booi_servers.map(x=>`<option>${esc(x)}</option>`).join('');state.server=$('#server').value;await loadPlayers();}catch(e){toast(e.message,true);$('#health').textContent='服务异常'}}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#view-'+b.dataset.view).classList.add('active');if(b.dataset.view==='accounts')loadAccounts();if(b.dataset.view==='catalog')loadCatalog()});
$('#server').onchange=()=>{state.server=$('#server').value;state.player=null;loadPlayers()};
$('#player-search').onclick=loadPlayers;$('#player-query').onkeydown=e=>{if(e.key==='Enter')loadPlayers()};
async function loadPlayers(){try{const d=await api(serverPath('players?q='+encodeURIComponent($('#player-query').value)));$('#player-list').innerHTML=d.players.map(p=>`<div class="record ${state.player==p.account_id?'active':''}" data-player="${p.account_id}"><b>${esc((p.family_name||'')+(p.name||'未命名'))}</b><span>#${p.account_id} · OpenID ${esc(p.openid)} · Lv.${p.level}</span></div>`).join('')||'<div class="empty">没有玩家</div>';$$('[data-player]').forEach(x=>x.onclick=()=>selectPlayer(x.dataset.player))}catch(e){toast(e.message,true)}}
async function selectPlayer(id){try{state.player=Number(id);state.data=await api(serverPath('players/'+id));$('#player-empty').hidden=true;$('#player-detail').hidden=false;renderPlayer();loadPlayers()}catch(e){toast(e.message,true)}}
function renderPlayer(){const p=state.data.profile;$('#player-head').innerHTML=`<div class="player-title"><div><h2>${esc((p.family_name||'')+(p.name||'未命名'))}</h2><p>#${p.account_id} · OpenID ${esc(p.openid)} · Zone ${p.zone_id}</p></div><div class="actions"><button id="complete-player" class="primary">完整账号</button><button id="import-player">导入抓包</button><button id="edit-profile">编辑资料</button><button id="ban-player">${state.data.ban?'解封':'封禁'}</button><button id="delete-player" class="danger">删除角色</button></div></div>`;$('#complete-player').onclick=completePlayer;$('#import-player').onclick=()=>$('#sync-import-file').click();$('#edit-profile').onclick=editProfile;$('#ban-player').onclick=toggleBan;$('#delete-player').onclick=deletePlayer;renderTab()}
$('#player-tabs').onclick=e=>{if(e.target.dataset.tab){state.tab=e.target.dataset.tab;$$('#player-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab));renderTab()}}
function renderTab(){const d=state.data,el=$('#player-content');if(state.tab==='overview'){el.innerHTML=`<div class="cards"><div class="metric"><label>猎人等级</label><strong>${d.profile.level}</strong></div><div class="metric"><label>思念数量</label><strong>${d.cards.length}</strong></div><div class="metric"><label>皮肤数量</label><strong>${d.fashions.length}</strong></div><div class="metric"><label>资产条目</label><strong>${d.assets.length}</strong></div><div class="metric"><label>当前剧情关卡</label><strong>${d.progress.current_stage_id||'-'}</strong></div><div class="metric"><label>账号状态</label><strong>${d.ban?'已封禁':'正常'}</strong></div></div>`;return}
if(state.tab==='assets'){el.innerHTML=`<div class="actions"><button id="add-asset" class="primary">添加资产</button></div>`+table(['类型','ID','数量','操作'],d.assets.map(a=>`<tr><td>${a.type}</td><td>${a.id}</td><td>${a.quantity}</td><td><button class="small" data-asset="${a.type}:${a.id}:${a.quantity}">编辑</button> <button class="small danger" data-delasset="${a.type}:${a.id}">删除</button></td></tr>`));$('#add-asset').onclick=()=>editAsset();$$('[data-asset]').forEach(x=>x.onclick=()=>editAsset(...x.dataset.asset.split(':').map(Number)));$$('[data-delasset]').forEach(x=>x.onclick=()=>deleteAsset(...x.dataset.delasset.split(':').map(Number)));return}
if(state.tab==='cards'){el.innerHTML=`<div class="actions"><button id="add-card" class="primary">添加思念</button></div>`+table(['ID','等级','经验','星级','进阶','觉醒','操作'],d.cards.map(a=>`<tr><td>${a.card_id}</td><td>${a.level}</td><td>${a.exp}</td><td>${a.star_level}</td><td>${a.rank_level}</td><td>${a.awaken?'是':'否'}</td><td><button class="small" data-card="${a.card_id}">编辑</button> <button class="small danger" data-delcard="${a.card_id}">删除</button></td></tr>`));$('#add-card').onclick=()=>editCard();$$('[data-card]').forEach(x=>x.onclick=()=>editCard(Number(x.dataset.card)));$$('[data-delcard]').forEach(x=>x.onclick=()=>deleteCard(Number(x.dataset.delcard)));return}
if(state.tab==='fashions'){el.innerHTML=`<div class="actions"><button id="add-fashion" class="primary">添加皮肤</button></div>`+table(['皮肤 ID','操作'],d.fashions.map(id=>`<tr><td>${id}</td><td><button class="small danger" data-delfashion="${id}">删除</button></td></tr>`));$('#add-fashion').onclick=()=>addFashion();$$('[data-delfashion]').forEach(x=>x.onclick=()=>deleteFashion(Number(x.dataset.delfashion)));return}
if(state.tab==='progress'){el.innerHTML=`<div class="cards"><div class="metric"><label>当前关卡</label><strong>${d.progress.current_stage_id||0}</strong></div><div class="metric"><label>主线选择关卡</label><strong>${d.progress.mainline_choose_stage_id||0}</strong></div><div class="metric"><label>已记录关卡</label><strong>${d.stages.length}</strong></div><div class="metric"><label>引导组</label><strong>${d.guides.length}</strong></div></div><div class="actions"><button id="edit-progress" class="primary">修改当前进度</button><button id="edit-stage">添加关卡</button><button id="edit-guide">添加引导</button><button id="edit-unlock">添加解锁</button><button id="edit-rolelove">添加羁绊</button></div>`+table(['关卡','状态','星数','奖励','操作'],d.stages.map(x=>`<tr><td>${x.stage_id}</td><td>${x.state}</td><td>${x.star}</td><td>${x.reward}</td><td><button class="small" data-stage="${x.stage_id}">编辑</button> <button class="small danger" data-delstate="stages:${x.stage_id}">删除</button></td></tr>`))+table(['引导组','步骤','状态','操作'],d.guides.map(x=>`<tr><td>${x.group_id}</td><td>${x.step_id}</td><td>${x.status}</td><td><button class="small" data-guide="${x.group_id}">编辑</button> <button class="small danger" data-delstate="guides:${x.group_id}">删除</button></td></tr>`))+table(['系统解锁','已读','操作'],d.unlocks.map(x=>`<tr><td>${x.unlock_id}</td><td>${x.is_read?'是':'否'}</td><td><button class="small" data-unlock="${x.unlock_id}">编辑</button> <button class="small danger" data-delstate="unlocks:${x.unlock_id}">删除</button></td></tr>`))+table(['男主','羁绊等级','羁绊值','操作'],d.role_love.map(x=>`<tr><td>${x.role_id}</td><td>${x.love_level}</td><td>${x.love_point}</td><td><button class="small" data-rolelove="${x.role_id}">编辑</button> <button class="small danger" data-delstate="role-love:${x.role_id}">删除</button></td></tr>`));$('#edit-progress').onclick=editProgress;$('#edit-stage').onclick=()=>editStage();$('#edit-guide').onclick=()=>editGuide();$('#edit-unlock').onclick=()=>editUnlock();$('#edit-rolelove').onclick=()=>editRoleLove();$$('[data-stage]').forEach(x=>x.onclick=()=>editStage(Number(x.dataset.stage)));$$('[data-guide]').forEach(x=>x.onclick=()=>editGuide(Number(x.dataset.guide)));$$('[data-unlock]').forEach(x=>x.onclick=()=>editUnlock(Number(x.dataset.unlock)));$$('[data-rolelove]').forEach(x=>x.onclick=()=>editRoleLove(Number(x.dataset.rolelove)));$$('[data-delstate]').forEach(x=>x.onclick=()=>deleteState(...x.dataset.delstate.split(':')));return}
if(state.tab==='tasks'){el.innerHTML=`<div class="actions"><button id="add-task" class="primary">添加/修改任务</button></div>`+table(['任务 ID','进度','领奖次数','完成时间','操作'],d.tasks.map(t=>`<tr><td>${t.task_id}</td><td>${t.num}</td><td>${t.reward_count}</td><td>${t.complete_time||'-'}</td><td><button class="small" data-task="${t.task_id}">编辑</button> <button class="small danger" data-deltask="${t.task_id}">删除</button></td></tr>`));$('#add-task').onclick=()=>editTask();$$('[data-task]').forEach(x=>x.onclick=()=>editTask(Number(x.dataset.task)));$$('[data-deltask]').forEach(x=>x.onclick=()=>deleteState('tasks',x.dataset.deltask));}
}
async function refreshPlayer(msg='已保存'){state.data=await api(serverPath('players/'+state.player));renderPlayer();toast(msg)}
async function editProfile(){const p=state.data.profile,f=prompt('姓氏',p.family_name);if(f===null)return;const n=prompt('名字',p.name);if(n===null)return;const l=Number(prompt('猎人等级',p.level));try{const r=await api(serverPath(`players/${state.player}/profile`),{method:'PATCH',body:JSON.stringify({family_name:f,name:n,level:l})});await refreshPlayer(`已保存，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function toggleBan(){try{if(state.data.ban){await api(serverPath(`players/${state.player}/ban`),{method:'DELETE'})}else{const message=prompt('封禁提示','管理员封禁');if(message===null)return;await api(serverPath(`players/${state.player}/ban`),{method:'PUT',body:JSON.stringify({EndTime:0,Reason:1,Message:message})})}await refreshPlayer()}catch(e){toast(e.message,true)}}
async function deletePlayer(){if(!confirm('确定删除此 BOOI 角色？该操作会解绑登录身份。'))return;try{await api(serverPath(`players/${state.player}`),{method:'DELETE'});state.player=null;state.data=null;$('#player-detail').hidden=true;$('#player-empty').hidden=false;await loadPlayers();toast('角色已删除')}catch(e){toast(e.message,true)}}
async function completePlayer(){if(!confirm('按当前 BOOI 资源版本发放全部思念、皮肤、物品、头像、头像框、称号与相关图鉴，并设为最高等级？'))return;try{toast('正在解析资源并写入账号…');const r=await api(`operations/booi/${encodeURIComponent(state.server)}/players/${state.player}/full-catalog`,{method:'POST',body:'{}'});await refreshPlayer(`完整账号已写入（资源 ${r.resource_version||'-'}），请重新登录客户端`) }catch(e){toast(e.message,true)}}
$('#sync-import-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||!confirm('导入会替换该账号的资产、思念、皮肤、任务、关卡、引导、解锁和羁绊状态，继续？'))return;const form=new FormData();form.append('file',file);try{toast('正在解析并导入账号…');const r=await api(`operations/booi/${encodeURIComponent(state.server)}/players/${state.player}/import-sync`,{method:'POST',body:form});await refreshPlayer(`导入完成：${r.counts.cards} 张思念、${r.counts.stages} 个关卡，请重新登录客户端`)}catch(err){toast(err.message,true)}};
async function editAsset(type,id,quantity){type=Number(prompt('资产类型',type||1));if(!type)return;id=Number(prompt('资产 ID',id||type));if(!id)return;quantity=Number(prompt('绝对数量',quantity??0));try{const r=await api(serverPath(`players/${state.player}/assets/${type}/${id}`),{method:'PUT',body:JSON.stringify({quantity})});await refreshPlayer(`资产已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function deleteAsset(type,id){if(!confirm(`删除资产 ${type}:${id}？`))return;try{const r=await api(serverPath(`players/${state.player}/assets/${type}/${id}`),{method:'DELETE'});await refreshPlayer(`资产已删除，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function editCard(id){const old=state.data.cards.find(x=>x.card_id===id)||{};id=Number(prompt('思念 ID',id||''));if(!id)return;const level=Number(prompt('等级',old.level||1)),star_level=Number(prompt('星级',old.star_level||1)),rank_level=Number(prompt('进阶等级',old.rank_level||0)),awaken=confirm('设为觉醒？');try{const r=await api(serverPath(`players/${state.player}/cards/${id}`),{method:'PUT',body:JSON.stringify({level,exp:0,star_level,rank_level,awaken})});await refreshPlayer(`思念已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function deleteCard(id){if(!confirm(`删除思念 ${id}？`))return;try{const r=await api(serverPath(`players/${state.player}/cards/${id}`),{method:'DELETE'});await refreshPlayer(`思念已删除，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function addFashion(id){id=Number(id||prompt('皮肤 ID'));if(!id)return;try{const r=await api(serverPath(`players/${state.player}/fashions/${id}`),{method:'PUT',body:'{}'});await refreshPlayer(`皮肤已发放，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function deleteFashion(id){if(!confirm(`删除皮肤 ${id}？`))return;try{await api(serverPath(`players/${state.player}/fashions/${id}`),{method:'DELETE'});await refreshPlayer('皮肤已删除；客户端将在下次同步刷新')}catch(e){toast(e.message,true)}}
async function editProgress(){const p=state.data.progress,current_stage_id=Number(prompt('当前关卡 ID',p.current_stage_id||0)),mainline_choose_stage_id=Number(prompt('主线选择关卡 ID',p.mainline_choose_stage_id||0));try{await api(serverPath(`players/${state.player}/progress`),{method:'PUT',body:JSON.stringify({current_stage_id,mainline_choose_stage_id})});await refreshPlayer('进度已保存；无独立推送的字段将在下次 Sync 刷新')}catch(e){toast(e.message,true)}}
async function editStage(id){const old=state.data.stages.find(x=>x.stage_id===id)||{};const stage_id=Number(id||prompt('关卡 ID'));if(!stage_id)return;const stateV=Number(prompt('状态',old.state??3)),star=Number(prompt('星数',old.star??3)),reward=Number(prompt('奖励状态',old.reward??1));try{const r=await api(serverPath(`players/${state.player}/stages/${stage_id}`),{method:'PUT',body:JSON.stringify({state:stateV,star,show_star:star,reward})});await refreshPlayer(`关卡已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function editGuide(id){const old=state.data.guides.find(x=>x.group_id===id)||{};const group_id=Number(id||prompt('引导组 ID'));if(!group_id)return;const step_id=Number(prompt('步骤 ID',old.step_id??0)),status=Number(prompt('状态',old.status??1));try{const r=await api(serverPath(`players/${state.player}/guides/${group_id}`),{method:'PUT',body:JSON.stringify({step_id,status})});await refreshPlayer(`引导已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function editUnlock(id){const old=state.data.unlocks.find(x=>x.unlock_id===id)||{};id=Number(id||prompt('系统解锁 ID'));if(!id)return;const is_read=confirm(old.is_read?'当前已读；保持已读？':'设为已读？');try{const r=await api(serverPath(`players/${state.player}/unlocks/${id}`),{method:'PUT',body:JSON.stringify({is_read})});await refreshPlayer(`解锁已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function editRoleLove(id){const old=state.data.role_love.find(x=>x.role_id===id)||{};id=Number(id||prompt('男主角色 ID'));if(!id)return;const love_level=Number(prompt('羁绊等级',old.love_level??1)),love_point=Number(prompt('羁绊值',old.love_point??0));try{const r=await api(serverPath(`players/${state.player}/role-love/${id}`),{method:'PUT',body:JSON.stringify({love_level,love_point})});await refreshPlayer(`羁绊已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
async function deleteState(section,key){if(!confirm(`删除 ${section}:${key}？`))return;try{await api(serverPath(`players/${state.player}/${section}/${key}`),{method:'DELETE'});await refreshPlayer('状态已删除；客户端将在下次同步校正删除结果')}catch(e){toast(e.message,true)}}
async function editTask(id){const old=state.data.tasks.find(x=>x.task_id===id)||{};id=Number(id||prompt('任务 ID'));if(!id)return;const num=Number(prompt('进度',old.num||0)),reward_count=Number(prompt('领奖次数',old.reward_count||0));try{const r=await api(serverPath(`players/${state.player}/tasks/${id}`),{method:'PUT',body:JSON.stringify({num,reward_count,complete_time:old.complete_time||0,has_got_next:!!old.has_got_next})});await refreshPlayer(`任务已更新，实时通知 ${r.notified} 个会话`)}catch(e){toast(e.message,true)}}
$('#new-player').onclick=async()=>{const openid=prompt('SDK OpenID（账号 ID）');if(!openid)return;const zone_id=Number(prompt('Zone ID',1));try{const r=await api(serverPath('players'),{method:'POST',body:JSON.stringify({openid,zone_id})});toast(r.created?'角色已创建':'角色已存在');await loadPlayers();selectPlayer(r.player.account_id)}catch(e){toast(e.message,true)}};
$('#account-search').onclick=loadAccounts;$('#account-query').onkeydown=e=>{if(e.key==='Enter')loadAccounts()};
async function loadAccounts(){try{const d=await api('sdk/accounts?q='+encodeURIComponent($('#account-query').value));$('#account-list').innerHTML=table(['ID / OpenID','手机号','创建时间','上次登录','操作'],d.accounts.map(a=>`<tr><td>${a.id}</td><td>${esc(a.phone)}</td><td>${new Date(a.created_at*1000).toLocaleString()}</td><td>${new Date(a.last_login_at*1000).toLocaleString()}</td><td><button class="small" data-editaccount="${a.id}:${esc(a.phone)}">编辑</button> <button class="small" data-session="${a.id}">签发登录</button> <button class="small danger" data-delaccount="${a.id}">删除</button></td></tr>`));$$('[data-editaccount]').forEach(x=>x.onclick=()=>editAccount(...x.dataset.editaccount.split(':')));$$('[data-session]').forEach(x=>x.onclick=()=>issueSession(x.dataset.session));$$('[data-delaccount]').forEach(x=>x.onclick=()=>deleteAccount(x.dataset.delaccount))}catch(e){toast(e.message,true)}}
$('#new-account').onclick=async()=>{const phone=prompt('中国大陆手机号');if(!phone)return;const password=prompt('初始密码（可留空）','');try{await api('sdk/accounts',{method:'POST',body:JSON.stringify({phone,password})});toast('SDK 账号已创建');loadAccounts()}catch(e){toast(e.message,true)}};
async function editAccount(id,phone){const next=prompt('手机号',phone);if(next===null)return;const password=prompt('新密码（留空表示清除密码；取消则不改）');const body={phone:next};if(password!==null)body.password=password;body.revoke_tokens=confirm('同时撤销现有登录令牌？');try{await api(`sdk/accounts/${id}`,{method:'PATCH',body:JSON.stringify(body)});toast('账号已更新');loadAccounts()}catch(e){toast(e.message,true)}}
async function issueSession(id){try{const d=await api(`sdk/accounts/${id}/session`,{method:'POST',body:'{}'});await navigator.clipboard.writeText(JSON.stringify(d));toast('新登录凭证已复制到剪贴板')}catch(e){toast(e.message,true)}}
async function deleteAccount(id){if(!confirm('确定删除 SDK 账号？BOOI 角色应先删除或解绑。'))return;try{await api(`sdk/accounts/${id}`,{method:'DELETE'});toast('SDK 账号已删除');loadAccounts()}catch(e){toast(e.message,true)}}
$('#catalog-search').onclick=loadCatalog;$('#catalog-query').onkeydown=e=>{if(e.key==='Enter')loadCatalog()};
async function loadCatalog(){if(!state.server)return;const kind=$('#catalog-kind').value,q=$('#catalog-query').value;try{const d=await api(serverPath(`catalog/${kind}?q=${encodeURIComponent(q)}&limit=300`));$('#catalog-list').innerHTML=`<div class="cards">${d.rows.map(row=>`<div class="resource"><small>${esc(kind)}</small><b title="${esc(row.localized_name||'未找到本地化名')}">${esc(row.localized_name||'未找到本地化名')}</b><span class="id">${esc(row.id)} · Text ${row.name_text_id||'-'}</span><footer>${catalogAction(kind,row.id,row.asset_type)}</footer></div>`).join('')}</div>`;$$('[data-grantcard]').forEach(x=>x.onclick=()=>withPlayer(()=>editCard(Number(x.dataset.grantcard))));$$('[data-grantfashion]').forEach(x=>x.onclick=()=>withPlayer(()=>addFashion(Number(x.dataset.grantfashion))));$$('[data-grantitem]').forEach(x=>x.onclick=()=>withPlayer(()=>editAsset(Number(x.dataset.type||0),Number(x.dataset.grantitem),0)));$$('[data-grantstage]').forEach(x=>x.onclick=()=>withPlayer(()=>editStage(Number(x.dataset.grantstage))));$$('[data-granttask]').forEach(x=>x.onclick=()=>withPlayer(()=>editTask(Number(x.dataset.granttask))));$$('[data-grantunlock]').forEach(x=>x.onclick=()=>withPlayer(()=>editUnlock(Number(x.dataset.grantunlock))));$$('[data-grantguide]').forEach(x=>x.onclick=()=>withPlayer(()=>editGuide(Number(x.dataset.grantguide))))}catch(e){toast(e.message,true)}}
function withPlayer(action){if(!state.player)return toast('请先选择玩家',true);action()}
function catalogAction(kind,id,type){if(kind==='cards')return `<button class="small primary" data-grantcard="${id}">发放</button>`;if(kind==='fashions')return `<button class="small primary" data-grantfashion="${id}">发放</button>`;if(kind==='items')return `<button class="small primary" data-type="${type||0}" data-grantitem="${id}">设置数量</button>`;if(kind==='stages')return `<button class="small primary" data-grantstage="${id}">设置</button>`;if(kind==='tasks')return `<button class="small primary" data-granttask="${id}">设置</button>`;if(kind==='unlocks')return `<button class="small primary" data-grantunlock="${id}">解锁</button>`;if(kind==='guides')return `<button class="small primary" data-grantguide="${id}">设置</button>`;return ''}
$('#catalog-kind').onchange=loadCatalog;
boot();
